# Generated by Django 4.2.6 on 2023-10-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="username")),
                ("password", models.CharField(max_length=64, verbose_name="password")),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("methane_concentration", models.FloatField()),
                ("formaldehyde_concentration", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="sensorread",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
                ("mvol", models.FloatField()),
                ("mppm", models.FloatField()),
                ("fvol", models.FloatField()),
                ("fppm", models.FloatField()),
                ("temp", models.IntegerField()),
                ("humd", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
