# Generated by Django 4.2.6 on 2023-10-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensorread",
            fields=[
                (
                    "time",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("mvol", models.FloatField()),
                ("mppm", models.FloatField()),
                ("fvol", models.FloatField()),
                ("fppm", models.FloatField()),
                ("temp", models.IntegerField()),
                ("humd", models.IntegerField()),
            ],
        ),
    ]
