# Generated by Django 4.2.6 on 2023-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_sensorread"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.CharField(max_length=18)),
                ("methane_ppm", models.FloatField()),
                ("formaldehyde_ppm", models.FloatField()),
                ("temperature", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(name="Sensorread",),
    ]
