# Generated by Django 4.2.6 on 2023-10-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_admin"),
    ]

    operations = [
        migrations.DeleteModel(name="sensorread",),
    ]
