# Generated by Django 4.2.6 on 2023-10-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_admin"),
        ("app01", "0004_sensorread"),
    ]

    operations = []
