# Generated by Django 4.2.6 on 2023-10-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_delete_sensorread"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensorread",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
                ("mvol", models.FloatField()),
                ("mppm", models.FloatField()),
                ("fvol", models.FloatField()),
                ("fppm", models.FloatField()),
                ("temp", models.IntegerField()),
                ("humd", models.IntegerField()),
            ],
        ),
    ]
